#!/bin/bash

. /etc/sboutils.conf

SBO_INFO="no"
SBO_DEPS="no"
SBO_DEPENDENTS="no"
SBO_FIND="no"

is_imput_empty(){
	if [ "$1" = "" ]; then
		echo "Input is empty. To view options, use `basename $0` help"
		exit 1
	fi
}

check_location(){
	if [ "$2" = "strict" ]; then
		LOCATION=$(cat $REPO/SLACKBUILDS.TXT | grep "/${1}$" | grep LOCATION | sed "s|SLACKBUILD LOCATION: ./||")
	else
		LOCATION=$(cat $REPO/SLACKBUILDS.TXT | grep -i "${1}" | grep LOCATION | sed "s|SLACKBUILD LOCATION: ./||")
	fi
	
	LOCATION_array=( $LOCATION )
	
	if [ "${#LOCATION_array[@]}" = "0" ] ; then
		echo "$1 not found on SlackBuilds.org! Exiting..."
		exit 1
	fi
}

location_search(){
	for i in ${LOCATION_array[@]}; do
		echo -e "$i"
	done
}

display_info(){
	. $REPO/$LOCATION/$1.info
	SHORTDESC=$(cat $REPO/$LOCATION/slack-desc | grep "${1}: ${1}" | sed "s|${1}: ||")
	CATEGORY=$(echo "$LOCATION" | sed "s:/$PRGNAM::")
	echo ""
	echo "$SHORTDESC"
	echo "Version:  $VERSION"
	echo "Category: $CATEGORY"
	echo "Homepage: $HOMEPAGE"

	echo ""
	cat $REPO/$LOCATION/README
	echo ""
	echo "--- direct dependencies: ([i] installed)"
}

display_requires(){
	requires_array=( $REQUIRES )

	for d in ${requires_array[@]}; do
		pkg=""
  
		# check if dependency ($d) is among installed pkgs
		installed=$(find /var/lib/pkgtools/packages/ -name "${d}-*" )
		installed_array=( $installed )
		if [ ! -z "$installed" ]; then
			for i in ${installed_array[@]}; do
				pkg+=$(echo "`basename ${i%-*-*-*}` ")
			done

			pkg_array=( $pkg )
			if [[ " ${pkg_array[*]} " =~ " ${d} " ]]; then
				echo "[i] $d"
			elif [[ ! " ${pkg_array[*]} " =~ " ${d} " ]]; then
				echo "[ ] $d"
			fi
		elif [ -z "$installed" ]; then
			echo "[ ] $d"
		fi
	done
}

hoorex_array(){
	if [ "$2" = "DEPS" ]; then
		hoorex=$(hoorex -r "$1")
	else
		hoorex=$(hoorex "$1")
	fi
		
	if [ -z "$hoorex" ]; then
		echo "$1 not found at SlackBuilds.org"
		exit 1
	fi

	hoorex_array=( $hoorex )
}

dependencies_title(){
	echo "--- dependencies: ([i] installed, [ ] not installed)"
}

hoorex_output(){
	for d in ${hoorex_array[@]}; do
		pkg=""
  
		# check if dependency ($d) is among installed pkgs
		installed=$(find /var/lib/pkgtools/packages/ -name "${d}-*" )
		installed_array=( $installed )
  
		if [ ! -z "$installed" ]; then
			for i in ${installed_array[@]}; do
			# Name can be tricky, think of <lignome> and <libgnome-keyring>...
			# So collect here all names that matched the search, removing the
			# full path and trimming the stuff separated by the last 3 dashes
			# in the package name.
				pkg+=$(echo "`basename ${i%-*-*-*}` ")
			done
			
			pkg_array=( $pkg )
    
			# search if array contains element or not
			# https://stackoverflow.com/a/15394738
			if [[ " ${pkg_array[*]} " =~ " ${d} " ]]; then
				echo "[i] $d"
			elif [[ ! " ${pkg_array[*]} " =~ " ${d} " ]]; then
				echo "[ ] $d"
			fi
		elif [ -z "$installed" ]; then
			echo "[ ] $d"
		fi
	done
}

helper() {
	echo "Usage: `basename $0` [task] SlackBuild"
	echo "Tasks:"
	echo "  info           display information about SlackBuild"
	echo "  dep            display dependencies chain for a SlackBuild"
	echo "  dependent      display what depends on a SlackBuild"
	echo "  find|search    search for a SlackBuild"         
	echo "  help           display this help message"
}

options(){
	case $1 in
		info)
			SBO_INFO="yes"
		;;
		dep)
			SBO_DEPS="yes"
		;;
		dependents)
			SBO_DEPENDENTS="yes"
		;;
		find|search)
			SBO_FIND="yes"
		;;
		help)
			helper
			exit 0
		;;
		*)
			echo "Unknown option $1"
			exit 1
		;;
  	esac

}

main(){
	options "$1" "$2"
	
	# $2 refers to position, e.g.: sboask info $2 (aka slackbuild),
	# but comes first after the function, so it is referred as $1
	# inside the corresponding functions! A note to my stupid self.
	if [ "$SBO_INFO" = "yes" ]; then
		check_location "$2" strict
		display_info "$2"
		display_requires "$2"
		exit 0
	fi
	if [ "$SBO_FIND" = "yes" ]; then
		check_location "$2" nonstrict
		location_search
		exit 0
	fi
	if [ "$SBO_DEPS" = "yes" ]; then
		check_location "$2" strict
		hoorex_array "$2" DEPS
		dependencies_title
		hoorex_output
		exit 0
	fi
	if [ "$SBO_DEPENDENTS" = "yes" ]; then
		check_location "$2" strict
		hoorex_array "$2" DEPENDENTS
		dependencies_title
		hoorex_output
		exit 0
	fi
	exit 0
}

is_imput_empty "$1"
main "$1" "$2"

# End of file
