#!/bin/bash

SLACKBUILD=$(basename $PWD)
echo "Processing $SLACKBUILD"

options() {
  while [ "$1" ]; do
    case $1 in
      -i|--install)
        PKGMK_INSTALL="install" ;;
      -u|--upgrade)
      -v|--version)
      echo "`basename $PKGMK_COMMAND` (pkgutils) $PKGMK_VERSION"
      exit 0 ;;
      -h|--help)
	print_help
	exit 0 ;;
	*)
	echo "`basename $PKGMK_COMMAND`: invalid option $1"
	exit 1 ;;
	esac
	shift
	done
}
