#!/bin/bash

PRGNAM=$(basename $PWD)

. /etc/sboutils.conf

SBO_TEMPLATE_AUTOTOOLS="no"
SBO_TEMPLATE_CMAKE="no"
SBO_TEMPLATE_HASKELL="no"
SBO_TEMPLATE_MESON="no"
SBO_TEMPLATE_PERL="no"
SBO_TEMPLATE_PYTHON="no"
SBO_TEMPLATE_RUBYGEM="no"
SBO_TEMPLATE_DOINST="no"
SBO_TEMPLATE_DOUNINST="no"
SBO_TEMPLATE_DESKTOP="no"
SBO_DOWNLOAD="no"
SBO_CHECK_MD5SUM="no"

check_input_files(){
	if [ ! -f $PRGNAM.SlackBuild ]; then
		echo "$PRGNAM.SlackBuild does not exist. Exiting."
		exit 1
	elif [ ! -f $PRGNAM.info ]; then
		echo "$PRGNAM.info does not exist. Exiting."
		exit 1
	elif [ ! -f slack-desc ]; then
		echo "slack-desk does not exist. Exiting."
		exit 1
	fi
}


TEMPLATES=/usr/share/sboutils/templates

helper() {
	echo "Run `basename $0` from within the SlackBuild folder."
	echo "Usage: `basename $0` [template] [options]"
	echo "Templates: auto (autotools), cmake, haskell, meson,"
	echo "           perl, python, ruby (rubygem)"
	echo "Options:"
	echo "  -di,  --doinst            copy doinst.sh file"
	echo "  -du,  --douninst          copy douninst.sh file"
	echo "  -de,  --desktop           copy template.desktop file"
	echo "  -um,  --update-md5        update sources md5sum"
	echo "  -h,   --help              print this help"
}

helper
