#!/bin/bash

# Is input empty?
if [ "$1" = "" ]; then
    echo "Input is empty. Usage: $(basename $0) [slackbuild...]"
    exit 1
fi

# No options used with revlibpkg
for t in "$@"; do
  if [ "${t:0:1}" = "-" ]; then
    echo -e "Invalid input $t. Usage: $(basename $0) [slackbuild...]"
    exit 1
  fi
done

hoorex=$(hoorex -r "$1")
hoorex_array=( $hoorex )

echo "--- dependencies: ([i] installed, [ ] not installed)"

for d in ${hoorex_array[@]}; do
  pkg=""
  
  # check if dependency ($d) is among installed pkgs
  installed=$(find /var/lib/pkgtools/packages/ -name "${d}-*" )
  installed_array=( $installed )
  
  if [ ! -z "$installed" ]; then
    for i in ${installed_array[@]}; do
      # Name can be tricky, think of <lignome> and <libgnome-keyring>...
      # So collect here all names that matched the search, removing the
      # full path and trimming the stuff separated by the last 3 dashes
      # in the package name.
      pkg+=$(echo "`basename ${i%-*-*-*}` ")
    done
    pkg_array=( $pkg )
    
    # search if array contains element or not
    # https://stackoverflow.com/a/15394738
    if [[ " ${pkg_array[*]} " =~ " ${d} " ]]; then
      echo "[i] $d"
    elif [[ ! " ${pkg_array[*]} " =~ " ${d} " ]]; then
      echo "[ ] $d"
    fi
  elif [ -z "$installed" ]; then
    echo "[ ] $d"
  fi
done
