#!/bin/bash

# Is input empty?
if [ "$1" = "" ]; then
    echo "Input is empty. Usage: $(basename $0) [slackbuild...]"
    exit 1
fi

# No options used with revlibpkg
for t in "$@"; do
  if [ "${t:0:1}" = "-" ]; then
    echo -e "Invalid input $t. Usage: $(basename $0) [slackbuild...]"
    exit 1
  fi
done

hoorex=$(hoorex "$1")
depnds=( $hoorex )
elements=${#depnds[@]}
# last element index
lastel="$(( $elements-1 ))"

installed=$(find /var/lib/pkgtools/packages/ -name "${depnds[0]}-*")
if [ -z "${depnds[0]}" ]; then
  echo "${1} not found on SBo. Exiting..."
  exit 0
elif [ ! -z "$installed" ]; then
    pkg=$(basename $installed)
    name=${pkg%-*-*-*}
    if [ "${depnds[0]}" = "$name" ]; then
      echo "[i] $name"
    elif [ "${depnds[0]}" != "$name" ]; then
      echo "[ ] ${depnds[0]}"
    fi
  elif [ -z "$installed" ]; then
    echo "[ ] ${depnds[0]}"
fi

for d in ${depnds[@]:1:$lastel}; do
  installed=$(find /var/lib/pkgtools/packages/ -name "${d}-*")
  if [ ! -z "$installed" ]; then
    pkg=$(basename $installed)
    name=${pkg%-*-*-*}
    if [ "$d" = "$name" ]; then
      echo "    [i] $name"
    elif [ "$d" != "$name" ]; then
      echo "    [ ] $d"
    fi
  elif [ -z "$installed" ]; then
    echo "    [ ] $d"
  fi
done
