#!/bin/bash

# Is input empty?
if [ "$1" = "" ]; then
    echo "Input is empty. Usage: $(basename $0) [template...]"
    exit 1
fi

CONF=/etc/sboutils.conf
TEMPLATES=/usr/share/sboutils/templates

. $CONF

PRGNAM=$(basename $PWD)
EMPTY="$(printf '%*s' ${#PRGNAM})"
YEAR=$(date +"%Y")

prepare(){
cp $TEMPLATES/$template-template.SlackBuild $PRGNAM.SlackBuild
sed -i "s:appname:$PRGNAM:g" $PRGNAM.SlackBuild
sed -i "s:<year>:$YEAR:" $PRGNAM.SlackBuild
sed -i "s:<you>:$MAINTAINER:" $PRGNAM.SlackBuild
sed -i "s:<where you live>:$LOCATION:" $PRGNAM.SlackBuild

sed -i '/# |--/,/# |--/d' $PRGNAM.SlackBuild

cp $TEMPLATES/slack-desc slack-desc
sed -i "s:appname:$PRGNAM:g" slack-desc
sed -i "s:       :$EMPTY:" slack-desc

cp $TEMPLATES/template.info $PRGNAM.info
sed -i "s:name of application:$PRGNAM:" $PRGNAM.info
sed -i "s:version of application::" $PRGNAM.info
sed -i 's:homepage of application::' $PRGNAM.info
sed -i 's:direct download link(s) of application source tarball(s), x86_64 only::' $PRGNAM.info
sed -i 's:direct download link(s) of application source tarball(s) arch-independent or x86::' $PRGNAM.info
sed -i 's:md5sum(s) of the source tarball(s) defined in DOWNLOAD_x86_64::' $PRGNAM.info
sed -i 's:md5sum(s) of the source tarball(s) defined in DOWNLOAD::' $PRGNAM.info
sed -i 's:%README%::' $PRGNAM.info
sed -i "s:name of SlackBuild script maintainer:$MAINTAINER:" $PRGNAM.info
sed -i "s:email address of author:$EMAIL:" $PRGNAM.info
}

while [ "$1" ]; do
  case $1 in
  auto)
    template=autotools
    prepare
    ;;
    
  cmake)
    template=cmake
    prepare
    ;;
  
  haskell)
    template=haskell
    prepare
    ;;
    
  meson)
    template=meson
    prepare
    ;;
    
  perl)
    template=perl
    prepare
    ;;
    
  python)
    template=python
    prepare
    ;;
    
  ruby)
    template=rubygem
    prepare
    ;;
    
  -di)
    cp $TEMPLATES/doinst.sh .
    ;;

  -du)
    cp $TEMPLATES/douninst.sh .
    ;;
  
  -de)
    cp $TEMPLATES/template.desktop $PRGNAM.desktop
    ;;

  *)
    echo "Unknown template/option:"
    echo "Templates: auto, cmake, haskell, meson, perl, python, ruby"
    echo "Options: -di (doinst.sh), -du (douninst.sh), -de (desktop)"
    ;;
  
  esac
  shift
done
