#!/bin/bash

PRGNAM=$(basename $PWD)

. /etc/sboutils.conf

SBO_INSTALL="no"
SBO_UPGRADE="no"
SBO_WARN="no"
SBO_REBUILD="no"
SBO_REINSTALL="no"
SBO_DOWNLOAD="no"
SBO_CHECK_MD5SUM="no"
SBO_DOWNLOAD_NO_CERTIFICATE="no"

check_input_files(){
	if [ ! -f $PRGNAM.SlackBuild ]; then
		echo "$PRGNAM.SlackBuild does not exist. Exiting."
		exit 1
	elif [ ! -f $PRGNAM.info ]; then
		echo "$PRGNAM.info does not exist. Exiting."
		exit 1
	elif [ ! -f slack-desc ]; then
		echo "slack-desk does not exist. Exiting."
		exit 1
	fi
}

load_info(){
	. $PRGNAM.info
}

does_package_exist(){
# what would be package name and search the installed packages database
	PACKAGE_NAME=$(PRINT_PACKAGE_NAME="true" bash ./$PRGNAM.SlackBuild)
	PACKAGE_INST=$(find /var/lib/pkgtools/packages/ -name "${PACKAGE_NAME%.*}")
}

load_sources(){
# Load sources and their md5sums as arrays
	read -r -d '' -a ARRAY_DOWNLOAD < <( echo "$DOWNLOAD" && printf '\0' )
	read -r -d '' -a ARRAY_DOWNLOAD_x86_64 < <( echo "$DOWNLOAD_x86_64" && printf '\0' )
	read -r -d '' -a ARRAY_MD5SUM < <( echo "$MD5SUM" && printf '\0' )
	read -r -d '' -a ARRAY_MD5SUM_x86_64 < <( echo "$MD5SUM_x86_64" && printf '\0' )
}

check_installpkg(){
	if [ ! -x "$(command -v installpkg)" ] || [ ! -x "$(command -v upgradepkg)" ]; then
		echo "<installpkg> and/or <upgradepkg> not in path/executable! Exiting."
		exit 1
	fi
}

package_exists(){
	if [ -f $PKGS/$PACKAGE_NAME ]; then
		echo "Package $PACKAGE_NAME exists in $PKGS"
	fi
}

package_installed(){
	if [ ! -z $PACKAGE_INST ]; then
		echo "Package $PACKAGE_NAME installed"
	fi
}

download_source(){

	if [ $SBO_DOWNLOAD_NO_CERTIFICATE = "yes" ]; then
		cert="--no-check-certificate"
	fi

	if [ ! -z "$DOWNLOAD" ] && [ ! "$DOWNLOAD" = "UNSUPPORTED" ] && [ ! "$DOWNLOAD" = "UNTESTED" ]; then
		for d in ${ARRAY_DOWNLOAD[@]}; do
			if [ -f `basename $d` ]; then
				echo "`basename $d`"
			else
				wget $cert -c $d
			fi
		done
	fi
	if [ ! -z "$DOWNLOAD_x86_64" ] && [ ! "$DOWNLOAD_x86_64" = "UNSUPPORTED" ] && [ ! "$DOWNLOAD_x86_64" = "UNTESTED" ]; then
		for d in ${ARRAY_DOWNLOAD_x86_64[@]}; do
			if [ -f `basename $d` ]; then
				echo "`basename $d`"
			else
				wget $cert -c $d
			fi
		done
	fi
}

check_md5sum_source(){
	if [ ! -z "$DOWNLOAD" ] && [ ! "$DOWNLOAD" = "UNSUPPORTED" ] && [ ! "$DOWNLOAD" = "UNTESTED" ]; then
		echo "---- check md5sum ([m] match, [e] mismatch, [ ] missing)"
		# determine position in array
		for (( d=0; d<${#ARRAY_DOWNLOAD[@]}; d++ )); do
			NAME_d=$(basename ${ARRAY_DOWNLOAD[$d]})
			if [ ! -f "$NAME_d" ]; then
				echo "[ ] ${ARRAY_DOWNLOAD[$d]}"
				exit 0
			elif [ -f "$NAME_d" ]; then
				MD5SUM_d=$(md5sum $NAME_d | awk '{print $1}')
				if [ "$MD5SUM_d" = "${ARRAY_MD5SUM[$d]}" ]; then
					echo "[m] $MD5SUM_d $NAME_d"
				elif [ "$MD5SUM_d" != "${ARRAY_MD5SUM[$d]}" ]; then
					echo "[e] ${ARRAY_DOWNLOAD[$d]}"
					exit 0
				fi
			fi
		done
	fi
}


build(){
	bash ./$PRGNAM.SlackBuild
}

install_package(){
	installpkg $PKGS/$PACKAGE_NAME
}

upgrade_package(){
	upgradepkg $PKGS/$PACKAGE_NAME
}

install_warn(){
	installpkg --warn $PKGS/$PACKAGE_NAME
}

reinstall_package(){
	upgradepkg --reinstall --install-new $PKGS/$PACKAGE_NAME
}

helper() {
	echo "Run `basename $0` from within the SlackBuild containing folder."
	echo "Usage: `basename $0` [options]"
	echo "Options:"
	echo "  -i,   --install           build and install package"
	echo "  -u,   --upgrade           build and upgrade package"
	echo "  -w,   --warn              warn if package will overwrite files"
	echo "  -r,   --rebuild           rebuild package"
	echo "  -ri,  --reinstall         rebuild and reinstall package"
	echo "  -d,   --download          download sources and exit"
	echo "  -nc,  --no-certificate    do not check download certificate"
	echo "  -cm,  --check-md5         check sources md5sum and exit"
	echo "  -h,   --help              print this help"
}

options(){
	while [ "$1" ]; do
		case $1 in
			-i|--install)
				SBO_INSTALL="yes"
			;;
  			-u|--upgrade)
				SBO_UPGRADE="yes"
			;;
			-w|--warn)
				SBO_WARN="yes"
			;;
			-r|--rebuild)
				SBO_REBUILD="yes"
			;;
			-ri|--reinstall)
				SBO_REINSTALL="yes"
			;;
			-d|--download)
				SBO_DOWNLOAD="yes"
			;;
			-nc|--no-certificate)
				SBO_DOWNLOAD_NO_CERTIFICATE="yes"
			;;
			-cm|--check-md5)
				SBO_CHECK_MD5SUM="yes"
			;;
			-h|--help)
				helper
				exit 0
			;;
			*)
				echo "Unknown option $1"
				exit 1
			;;
  		esac
	shift
	done
}

main(){
	options "$@"

	check_input_files
	load_info
	does_package_exist
	load_sources

	# functions to execute pre-build
	if [ $SBO_DOWNLOAD = "yes" ]; then
		download_source
		exit 0
	fi
	
	if [ $SBO_CHECK_MD5SUM = "yes" ]; then
		check_md5sum_source
		exit 0
	fi
	
	# build, install and upgrade functions below cannot be used as regular user
	check_installpkg
	
	if [ -f $PKGS/$PACKAGE_NAME ] || [ ! -z "$PACKAGE_INST" ] && [ "$SBO_REBUILD" = "no" ] && [ "$SBO_REINSTALL" = "no" ]; then
		package_exists
		package_installed
		echo "Use -r or -ri options to rebuild."
		exit 0
	else
		download_source
		check_md5sum_source
		build
	fi
	
	# functions to execute post-build
	if [ "$SBO_INSTALL" = "yes" ]; then
		install_package
		exit 0
	fi

	if [ "$SBO_REINSTALL" = "yes" ]; then
		install_package
		exit 0
	fi

	if [ "$SBO_UPGRADE" = "yes" ]; then
		upgrade_package
		exit 0
	fi

	if [ "$SBO_WARN" = "yes" ]; then
		install_warn
		exit 0
	fi

	if [ "$SBO_REINSTALL" = "yes" ]; then
		reinstall_package
		exit 0
	fi

	exit 0
}

main "$@"

# End of file
