#!/bin/bash

DIRNAM=$(basename $PWD)

. /etc/sboutils.conf

SBO_INSTALL="no"
SBO_UPGRADE="no"
SBO_DOWNLOAD="no"
SBO_DOWNLOAD_NO_CERTIFICATE="no"
SBO_FORCE="no"

check_folder() {
	if [ ! -d $1 ]; then
		echo "Folder '$1' does not exist."
		exit 1
	elif [ ! -w $1 ]; then
		echo "Folder '$1' not writable."
		exit 1
	elif [ ! -x $1 ] || [ ! -r $1 ]; then
		echo "Folder '$1' not readable."
		exit 1
	fi
}

check_files() {
	if [ ! -f $1 ]; then
		echo "File $1 does not exist."
		exit 1
	elif [ -e $1 ] && [ ! -w $1 ]; then
		echo "File $1 is not writable."
		exit 1
	elif [ ! -r $1 ]; then
		echo "File $1 is not readable."
		exit 1
	fi
}

check_installpkg(){
	if [ ! -x "$(command -v installpkg)" ] || [ ! -x "$(command -v upgradepkg)" ]; then
		echo "<installpkg> and/or <upgradepkg> not in path/executable! Exiting."
		exit 1
	fi
}

load_info(){
	. $DIRNAM.info
	if [ "$DIRNAM" != "$PRGNAM" ]; then
		echo "SlackBuild folder name is different than PRGNAM!"
		exit 1
	fi
}

check_additional_files(){
	additional=$(grep "$1" $PRGNAM.SlackBuild)
	
	if [ ! -z "$additional" ]; then
		check_files $1
	fi
}

does_package_exist(){
# what would be package name and search the installed packages database
	PACKAGE_NAME=$(PRINT_PACKAGE_NAME="true" bash ./$PRGNAM.SlackBuild)
	PACKAGE_INST=$(find /var/lib/pkgtools/packages/ -name "${PACKAGE_NAME%.*}")
}

load_sources(){
	if [ "$ARCH" = "x86" ] && [ "$DOWNLOAD" = "UNSUPPORTED" ]; then
		echo "$ARCH is not supported"
		exit 0
	fi
	if [ "$ARCH" = "x86_64" ] && [ "$DOWNLOAD_x86_64" = "UNSUPPORTED" ]; then
		echo "$ARCH is not supported"
		exit 0
	fi
	if [ "$ARCH" = "x86_64" ] && [ "$DOWNLOAD_x86_64" = "UNTESTED" ]; then
		echo "$ARCH is untested"
		exit 0
	fi
	
	if [ "$ARCH" = "x86_64" ] && [ ! -z $DOWNLOAD_x86_64 ]; then
		read -r -d '' -a ARRAY_DOWNLOAD < <( echo "$DOWNLOAD_x86_64" && printf '\0' )
		read -r -d '' -a ARRAY_MD5SUM < <( echo "$MD5SUM_x86_64" && printf '\0' )
	else
		read -r -d '' -a ARRAY_DOWNLOAD < <( echo "$DOWNLOAD" && printf '\0' )
		read -r -d '' -a ARRAY_MD5SUM < <( echo "$MD5SUM" && printf '\0' )
	fi
}

package_exists(){
	if [ -f "$PKGS/$PACKAGE_NAME" ]; then
		echo "Package $PACKAGE_NAME exists in $PKGS"
	fi
}

package_installed(){
	if [ ! -z "$PACKAGE_INST" ]; then
		echo "Package $PACKAGE_NAME installed"
	fi
}

download_source(){
	# some sources (e.g. geneconv) need this to be downloaded
	if [ $SBO_DOWNLOAD_NO_CERTIFICATE = "yes" ]; then
		cert="--no-check-certificate"
	fi
	
	local -n local_array_download=$1
	for (( d=0; d<${#local_array_download[@]}; d++ )); do
		NAME_d=$(basename ${local_array_download[$d]} | sed 's:%20:\ :g')
		if [ -f "$NAME_d" ] && [ "$SBO_FORCE" = "no" ]; then
			echo "[d] $NAME_d"
		elif [ -f "$NAME_d" ] && [ "$SBO_FORCE" = "yes" ]; then
			echo "[o] $NAME_d"
			wget $cert -c "${local_array_download[$d]}"
		else
			echo "[ ] $NAME_d"
			wget $cert -c "${local_array_download[$d]}"
		fi
	done
}

check_md5sum_source(){
	local -n local_array_download=$1 # ARRAY_DOWNLOAD(_x86_64)
	local -n local_array_md5sum=$2 # ARRAY_MD5SUM(_x86_64)
	
	md5summary=""
	# determine position in array
	for (( d=0; d<${#local_array_download[@]}; d++ )); do
		NAME_d=$(basename ${local_array_download[$d]} | sed 's:%20:\ :g')
		if [ ! -f "$NAME_d" ]; then
			# echo "[ ] ${local_array_download[$d]}"
			#exit 0
			echo "[ ] $NAME_d"
			md5summary+="missing "
		elif [ -f "$NAME_d" ]; then
			MD5SUM_d=$(md5sum "$NAME_d" | awk '{print $1}')
			if [ "$MD5SUM_d" = "${local_array_md5sum[$d]}" ]; then
				#echo "[m] $MD5SUM_d $NAME_d"
				echo "[m] $NAME_d"
			elif [ "$MD5SUM_d" != "${local_array_md5sum[$d]}" ]; then
				#echo "[e] ${local_array_download[$d]}"
				#exit 0
				echo "[e] $NAME_d"
				md5summary+="error "
			fi
		fi
	done
	md5summary_array=( $md5summary )
}

report_md5sum_source(){
	if [[ " ${md5summary_array[*]} " =~ " missing " ]] || [[ " ${md5summary_array[*]} " =~ " error " ]]; then
		echo "Download sources missing or have md5sum mismatch!"
		exit 1
	fi
}

download_source_title(){
	echo "--- download ([d] already downloaded, [o] overwrite downloaded, [ ] missing)"
}
check_md5sum_source_title(){
	echo "--- check md5sum ([m] match, [e] error (mismatch), [ ] source missing)"
}

build(){
	bash ./$PRGNAM.SlackBuild
}

install_package(){
	installpkg $PKGS/$PACKAGE_NAME
}

upgrade_package(){
	upgradepkg $PKGS/$PACKAGE_NAME
}

install_warn(){
	overwrite=$(installpkg --warn $PKGS/$PACKAGE_NAME)
	if [ ! -z "$overwrite" ]; then
		printf '%s\n' "$overwrite"
		echo "Files will be overwritten!"
		exit 0
	else
		echo "installpkg --warn check passed"
	fi
}

reinstall_package(){
	upgradepkg --reinstall --install-new $PKGS/$PACKAGE_NAME
}

helper() {
	echo "Run `basename $0` from within the SlackBuild containing folder."
	echo "Usage: `basename $0` [options]"
	echo "Options:"
	echo "  -i,   --install           build and install package"
	echo "  -u,   --upgrade           build and upgrade package"
	echo "  -d,   --download          download and check sources for $ARCH and exit"
	echo "  -nc,  --no-certificate    do not check download certificate"
	echo "  -f    --force             force operation"
	echo "  -h,   --help              print this help"
}

options(){
	while [ "$1" ]; do
		case $1 in
			-i|--install)
				SBO_INSTALL="yes"
			;;
  			-u|--upgrade)
				SBO_UPGRADE="yes"
			;;
			-d|--download)
				SBO_DOWNLOAD="yes"
			;;
			-nc|--no-certificate)
				SBO_DOWNLOAD_NO_CERTIFICATE="yes"
			;;
			-f|--force)
				SBO_FORCE="yes"
			;;
			-h|--help)
				helper
				exit 0
			;;
			*)
				echo "Unknown option $1"
				exit 1
			;;
  		esac
	shift
	done
}

main(){
	options "$@"
	check_folder $PWD
	check_folder $BUILD
	check_files $DIRNAM.SlackBuild
	check_files $DIRNAM.info
	load_info
	check_files slack-desc
	check_additional_files doinst.sh
	check_additional_files douninst.sh
	does_package_exist
	load_sources

	# functions to execute pre-build
	if [ $SBO_DOWNLOAD = "yes" ]; then
		download_source_title
		download_source ARRAY_DOWNLOAD
		check_md5sum_source_title
		check_md5sum_source ARRAY_DOWNLOAD ARRAY_MD5SUM
		exit 0
	fi
	
	# build, install and upgrade functions below cannot be used as regular user
	check_installpkg
	
	if [ -f $PKGS/$PACKAGE_NAME ] && [ -z "$PACKAGE_INST" ] && [ "$SBO_INSTALL" = "yes" ]; then
		install_warn
		install_package
		exit 0
	fi
	
	if [ -f $PKGS/$PACKAGE_NAME ] || [ ! -z "$PACKAGE_INST" ] && [ "$SBO_FORCE" = "no" ]; then
		package_exists
		package_installed
		echo "Use -f option to rebuild"
		exit 0
	else
		download_source_title
		download_source ARRAY_DOWNLOAD
		check_md5sum_source_title
		check_md5sum_source ARRAY_DOWNLOAD ARRAY_MD5SUM
		report_md5sum_source
		build
		install_warn
	fi
	
	# functions to execute post-build
	if [ "$SBO_INSTALL" = "yes" ]; then
		install_package
		exit 0
	fi

	if [ "$SBO_UPGRADE" = "yes" ]; then
		upgrade_package
		exit 0
	fi

	if [ "$SBO_REINSTALL" = "yes" ]; then
		reinstall_package
		exit 0
	fi

	exit 0
}

main "$@"

# End of file
